/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package com.vladplay.mfte.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import com.vladplay.mfte.item.*;
import com.vladplay.mfte.MorefoodthaneverMod;

public class MorefoodthaneverModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, MorefoodthaneverMod.MODID);
	public static final RegistryObject<Item> CHOCOLATE;
	public static final RegistryObject<Item> CHOCOLATE_CHIP;
	public static final RegistryObject<Item> DOUGH;
	public static final RegistryObject<Item> COOKIE_DOUGH;
	public static final RegistryObject<Item> FLOUR;
	public static final RegistryObject<Item> YEAST;
	public static final RegistryObject<Item> SALT;
	public static final RegistryObject<Item> OIL_BOTTLE;
	public static final RegistryObject<Item> BUTTER;
	public static final RegistryObject<Item> CREAM_BUCKET;
	public static final RegistryObject<Item> CACAO_BUTTER_BOTTLE;
	public static final RegistryObject<Item> CACAO_BUTTER;
	public static final RegistryObject<Item> BAKED_POISONOUS_POTATO;
	public static final RegistryObject<Item> POISONOUS_POTATO_STEW;
	public static final RegistryObject<Item> POISONOUS_POTATO_NUBS;
	public static final RegistryObject<Item> POTATO_STEW;
	public static final RegistryObject<Item> CANDY;
	public static final RegistryObject<Item> CUPCAKE;
	public static final RegistryObject<Item> GELATIN;
	public static final RegistryObject<Item> ACTUAL_CHOCOLATE;
	public static final RegistryObject<Item> CHOCOLATE_DOUGH;
	public static final RegistryObject<Item> CAKE_LAYER;
	public static final RegistryObject<Item> INSTANT_CAKE;
	public static final RegistryObject<Item> CAKE_SLICE;
	public static final RegistryObject<Item> CUPCAKE_LAYER;
	public static final RegistryObject<Item> SWEET_BERRY;
	public static final RegistryObject<Item> SWEET_BERRY_BOTTLE;
	public static final RegistryObject<Item> MARSHMALLOW;
	public static final RegistryObject<Item> MARSHMALLOW_STICK;
	public static final RegistryObject<Item> ROASTED_MARSHMALLOW_STICK;
	public static final RegistryObject<Item> WELLDONE_MARSHMALLOW;
	public static final RegistryObject<Item> BURNT_MARSHMALLOW_STICK;
	public static final RegistryObject<Item> RAW_BISCUIT;
	public static final RegistryObject<Item> BISCUIT;
	public static final RegistryObject<Item> SMORE;
	public static final RegistryObject<Item> ROASTED_SMORE;
	public static final RegistryObject<Item> WELLDONE_SMORE;
	public static final RegistryObject<Item> BURNT_SMORE;
	public static final RegistryObject<Item> GIANT_SMORE;
	public static final RegistryObject<Item> PINEAPPLE;
	public static final RegistryObject<Item> PINEAPPLE_SEEDS;
	public static final RegistryObject<Item> JELLY_JAR;
	public static final RegistryObject<Item> JELLYFISH;
	public static final RegistryObject<Item> JELLYFISH_JELLY;
	public static final RegistryObject<Item> KRABBY_PATTY;
	public static final RegistryObject<Item> PATTY;
	public static final RegistryObject<Item> TOMATO;
	public static final RegistryObject<Item> KETCHUP_BOTTLE;
	public static final RegistryObject<Item> PLASTIC_CONDIMENT_BOTTLE;
	public static final RegistryObject<Item> MUSTARD_BOTTLE;
	public static final RegistryObject<Item> MUSTARD_SEEDS;
	public static final RegistryObject<Item> CHEESE_BUCKET;
	public static final RegistryObject<Item> CHEESE;
	public static final RegistryObject<Item> LETTUCE;
	public static final RegistryObject<Item> ONION;
	public static final RegistryObject<Item> TOP_BUN;
	public static final RegistryObject<Item> BOTTOM_BUN;
	public static final RegistryObject<Item> SESAME_SEEDS;
	public static final RegistryObject<Item> SESAME_BUN;
	public static final RegistryObject<Item> KRABBY_PIZZA;
	public static final RegistryObject<Item> PIZZA_CRUST;
	public static final RegistryObject<Item> PEPPERONI;
	public static final RegistryObject<Item> RAW_KRABBY_PIZZA;
	public static final RegistryObject<Item> MAYONNAISE_JAR;
	public static final RegistryObject<Item> EMPTY_MAYO_JAR;
	public static final RegistryObject<Item> VINEGAR_BOTTLE;
	public static final RegistryObject<Item> RAW_SESAME_BUN;
	public static final RegistryObject<Item> RAW_BOTTOM_BUN;
	public static final RegistryObject<Item> PLASTIC_ORE;
	public static final RegistryObject<Item> DEEPSLATE_PLASTIC_ORE;
	public static final RegistryObject<Item> PLASTIC;
	public static final RegistryObject<Item> RED_PLASTIC;
	public static final RegistryObject<Item> BLUE_PLASTIC;
	public static final RegistryObject<Item> FROZEN_PATTY;
	public static final RegistryObject<Item> LAVA_CHICKEN;
	public static final RegistryObject<Item> TATER_TOTS;
	public static final RegistryObject<Item> CANDY_WRAPPER;
	public static final RegistryObject<Item> FROZEN_PATTY_BOX;
	public static final RegistryObject<Item> MAYONNAISE_LABEL;
	public static final RegistryObject<Item> CARDBOARD;
	public static final RegistryObject<Item> CHUM_BUCKET;
	public static final RegistryObject<Item> BIG_MAC_SAUCE;
	public static final RegistryObject<Item> BLACK_PLASTIC;
	public static final RegistryObject<Item> GARLIC_POWDER;
	public static final RegistryObject<Item> ONION_POWDER;
	public static final RegistryObject<Item> PAPRIKA;
	public static final RegistryObject<Item> GARLIC;
	public static final RegistryObject<Item> BELL_PEPPER;
	public static final RegistryObject<Item> SALT_PEPPER;
	public static final RegistryObject<Item> CHILI_PEPPER;
	public static final RegistryObject<Item> PEPPER;
	public static final RegistryObject<Item> BIG_MAC;
	public static final RegistryObject<Item> RAW_CENTER_BUN;
	public static final RegistryObject<Item> CENTER_BUN;
	public static final RegistryObject<Item> FRENCH_FRY_BOX;
	public static final RegistryObject<Item> FRENCH_FRIES;
	public static final RegistryObject<Item> MC_NUGGETS;
	public static final RegistryObject<Item> GLASS_CUP;
	public static final RegistryObject<Item> VANILLA;
	public static final RegistryObject<Item> ICE_CREAM_BUCKET;
	public static final RegistryObject<Item> BLUEBERRIES;
	public static final RegistryObject<Item> RASPBERRY;
	public static final RegistryObject<Item> STRAWBERRY;
	public static final RegistryObject<Item> GRIMACE_SHAKE;
	public static final RegistryObject<Item> STRAW;
	public static final RegistryObject<Item> YELLOW_PLASTIC;
	public static final RegistryObject<Item> NETHER_FLAME_SAUCE;
	public static final RegistryObject<Item> SAUCE_CONTAINER;
	public static final RegistryObject<Item> BURGER_CRYSTAL;
	public static final RegistryObject<Item> CAYENNE_PEPPER;
	public static final RegistryObject<Item> TOMATO_PASTE;
	public static final RegistryObject<Item> SALT_SUGAR;
	public static final RegistryObject<Item> RAW_BUN;
	public static final RegistryObject<Item> MUG;
	public static final RegistryObject<Item> COFFEE_BEANS;
	public static final RegistryObject<Item> COFFEE_MUG;
	public static final RegistryObject<Item> GLOW_DYE;
	public static final RegistryObject<Item> GLOWING_BERRY;
	public static final RegistryObject<Item> GLOWING_CARROT;
	public static final RegistryObject<Item> GLOWING_FISH;
	public static final RegistryObject<Item> GLOWING_BONE;
	public static final RegistryObject<Item> BOGGED_MOSS;
	public static final RegistryObject<Item> CRACKED_WITHER_SKULL;
	public static final RegistryObject<Item> ELDER_GUARDIAN_EYE;
	public static final RegistryObject<Item> ENDER_DRAGON_HAUNCH;
	public static final RegistryObject<Item> ENDER_SHELL;
	public static final RegistryObject<Item> EVOKER_FANG;
	public static final RegistryObject<Item> CREAKING_BARK;
	public static final RegistryObject<Item> GUARDIAN_EYE;
	public static final RegistryObject<Item> HOGLIN_MEAT;
	public static final RegistryObject<Item> ILLAGER_SHANK;
	public static final RegistryObject<Item> PIGLIN_NOSE;
	public static final RegistryObject<Item> RAVAGER_HAUNCH;
	public static final RegistryObject<Item> SILVERFISH_SHELL;
	public static final RegistryObject<Item> SHULKER_GOO;
	public static final RegistryObject<Item> VEX_WING;
	public static final RegistryObject<Item> WARDEN_HORN;
	public static final RegistryObject<Item> WITHERED_BONE;
	public static final RegistryObject<Item> ENDER_SPICE;
	public static final RegistryObject<Item> NETHER_SPICE;
	public static final RegistryObject<Item> OMINOUS_SPICE;
	public static final RegistryObject<Item> BATTERED_BREEZE_BALLS;
	public static final RegistryObject<Item> BLAZE_COCOA;
	public static final RegistryObject<Item> BOGGED_STEW;
	public static final RegistryObject<Item> BONE_SHAKE;
	public static final RegistryObject<Item> BOOMSTICK_POPSICLE;
	public static final RegistryObject<Item> BRAIN_JUICE;
	public static final RegistryObject<Item> CRISPY_HORSE_RIBS;
	public static final RegistryObject<Item> CRUNCHY_CUPCAKE;
	public static final RegistryObject<Item> DRAGON_HOTPOT;
	public static final RegistryObject<Item> DROWNED_STEW;
	public static final RegistryObject<Item> ELDER_GUARDIAN_SUSHI;
	public static final RegistryObject<Item> ENDER_LEMONADE;
	public static final RegistryObject<Item> ENDER_EYE_SKEWER;
	public static final RegistryObject<Item> FRIED_BONE_CHIPS;
	public static final RegistryObject<Item> GHOST_CAKE;
	public static final RegistryObject<Item> GLAZED_ILLAGE_SKEWER;
	public static final RegistryObject<Item> GREEN_HAM_AND_EGGS;
	public static final RegistryObject<Item> GUARDIAN_BROTH;
	public static final RegistryObject<Item> MUMMY_WRAP;
	public static final RegistryObject<Item> GUARDIAN_SUSHI;
	public static final RegistryObject<Item> HOGLIN_BROTH;
	public static final RegistryObject<Item> HOT_CHOCOLATE_CHURRO;
	public static final RegistryObject<Item> ILLAGE_BURGER;
	public static final RegistryObject<Item> MAGMA_CREAM_COB;
	public static final RegistryObject<Item> NIGHTMARE_BOBA_TEA;
	public static final RegistryObject<Item> OMINOUS_BERRY_PIE;
	public static final RegistryObject<Item> PIGLIN_PIZZA;
	public static final RegistryObject<Item> POISONED_CREAM_CONE;
	public static final RegistryObject<Item> RAVAGER_STEAK;
	public static final RegistryObject<Item> ROTTEN_NOSEMALLOW;
	public static final RegistryObject<Item> ROTTEN_RIBS;
	public static final RegistryObject<Item> SHULKER_SPAGHETTI;
	public static final RegistryObject<Item> SILVER_SEAFOOD;
	public static final RegistryObject<Item> SLIME_STEW;
	public static final RegistryObject<Item> SODA_BREEZE;
	public static final RegistryObject<Item> SOUL_FLASK;
	public static final RegistryObject<Item> SOUL_SLORP;
	public static final RegistryObject<Item> STUFFED_ENDERMITE;
	public static final RegistryObject<Item> STUFFED_STUMP;
	public static final RegistryObject<Item> SWAMP_LATTE;
	public static final RegistryObject<Item> VEXED_SANDWICH;
	public static final RegistryObject<Item> WARDEN_CAKE;
	public static final RegistryObject<Item> WEBBED_CREAM_CONE;
	public static final RegistryObject<Item> WINTER_WRAP;
	public static final RegistryObject<Item> WITHER_SKULL_SUB;
	public static final RegistryObject<Item> WITHERED_BONEDOG;
	public static final RegistryObject<Item> COCOA_MUG;
	public static final RegistryObject<Item> LEMON_SLICE;
	public static final RegistryObject<Item> GRAPEFRUIT_SLICE;
	public static final RegistryObject<Item> LAVENDER;
	public static final RegistryObject<Item> MINT;
	public static final RegistryObject<Item> PINE_OIL;
	public static final RegistryObject<Item> SEAWEED;
	public static final RegistryObject<Item> YLANG_YLANG;
	public static final RegistryObject<Item> BENZOIN;
	public static final RegistryObject<Item> CEDARWOOD;
	public static final RegistryObject<Item> TONKA;
	public static final RegistryObject<Item> OAKMOSS;
	public static final RegistryObject<Item> PINEAPPLE_PEEL;
	public static final RegistryObject<Item> CONSUMABLE_SUGAR;
	public static final RegistryObject<Item> CONSUMABLE_SUGAR_CANE;
	public static final RegistryObject<Item> ORANGE_SLICE;
	public static final RegistryObject<Item> SODA_POTION;
	public static final RegistryObject<Item> DYNAMITE;
	public static final RegistryObject<Item> WAX_BLOCK;
	public static final RegistryObject<Item> FRIED_EGG;
	public static final RegistryObject<Item> EDIBLE_KELP;
	public static final RegistryObject<Item> EDIBLE_NETHER_WART;
	public static final RegistryObject<Item> DRINKABLE_WATER_BUCKET;
	public static final RegistryObject<Item> EDIBLE_SNOWBALL;
	public static final RegistryObject<Item> EDIBLE_WHEAT_SEEDS;
	public static final RegistryObject<Item> EDIBLE_MELON_SEEDS;
	public static final RegistryObject<Item> EDIBLE_PUMPKIN_SEEDS;
	public static final RegistryObject<Item> EDIBLE_BEETROOT_SEEDS;
	public static final RegistryObject<Item> EDIBLE_POWDER_SNOW_BUCKET;
	public static final RegistryObject<Item> EDIBLE_COCOA_BEANS;
	public static final RegistryObject<Item> EDIBLE_HONEYCOMB;
	public static final RegistryObject<Item> EDIBLE_EGG;
	public static final RegistryObject<Item> EGG_SHELL;
	public static final RegistryObject<Item> EDIBLE_TURTLE_EGG;
	public static final RegistryObject<Item> TURTLE_EGG_SHELL;
	public static final RegistryObject<Item> CRYSTALLIZED_HONEY;
	public static final RegistryObject<Item> BANANA;
	public static final RegistryObject<Item> NACHO;
	public static final RegistryObject<Item> CORN;
	public static final RegistryObject<Item> BLACKBERRY;
	public static final RegistryObject<Item> GRAPES;
	public static final RegistryObject<Item> PEANUT;
	public static final RegistryObject<Item> PEANUT_SHELL;
	public static final RegistryObject<Item> CUCUMBER;
	public static final RegistryObject<Item> CRANBERRIES;
	public static final RegistryObject<Item> TURNIP;
	public static final RegistryObject<Item> KIWI;
	public static final RegistryObject<Item> TURMERIC;
	public static final RegistryObject<Item> LIME_SLICE;
	public static final RegistryObject<Item> LEMON;
	public static final RegistryObject<Item> GRAPEFRUIT;
	public static final RegistryObject<Item> ORANGE;
	public static final RegistryObject<Item> LIME;
	public static final RegistryObject<Item> PEAR;
	public static final RegistryObject<Item> PEACH;
	public static final RegistryObject<Item> AVOCADO;
	public static final RegistryObject<Item> COCONUT;
	public static final RegistryObject<Item> COCONUT_SHELL;
	public static final RegistryObject<Item> COCONUT_HALF;
	public static final RegistryObject<Item> CHERRIES;
	public static final RegistryObject<Item> OLIVES;
	public static final RegistryObject<Item> POMEGRANATE;
	public static final RegistryObject<Item> ACORN;
	public static final RegistryObject<Item> PLUM;
	public static final RegistryObject<Item> PITAHAYA;
	public static final RegistryObject<Item> PITAHAYA_PEEL;
	public static final RegistryObject<Item> AVOCADO_HALF;
	public static final RegistryObject<Item> AVOCADO_PEEL;
	public static final RegistryObject<Item> AVOCADO_PEEL_HALF;
	public static final RegistryObject<Item> COCONUT_SHELL_HALF;
	public static final RegistryObject<Item> KIWIFRUIT;
	public static final RegistryObject<Item> TEA_LEAVES;
	public static final RegistryObject<Item> RAW_TORTILLA;
	public static final RegistryObject<Item> TORTILLA;
	public static final RegistryObject<Item> TORTILLA_CHIP;
	public static final RegistryObject<Item> MANGO;
	public static final RegistryObject<Item> MANGO_SKIN;
	public static final RegistryObject<Item> GREEN_BEAN;
	public static final RegistryObject<Item> SOUR_BERRIES;
	public static final RegistryObject<Item> SOUR_BERRY_BUSH;
	public static final RegistryObject<Item> SOYBEAN_POD;
	public static final RegistryObject<Item> SOYBEANS;
	public static final RegistryObject<Item> COOKED_SOYBEANS;
	public static final RegistryObject<Item> EMPTY_SOYBEAN_POD;
	public static final RegistryObject<Item> HUCKLEBERRIES;
	public static final RegistryObject<Item> CHOCOLATE_STRAWBERRY;
	public static final RegistryObject<Item> PRICKLY_PEAR;
	public static final RegistryObject<Item> LINGONBERRIES;
	public static final RegistryObject<Item> CANTALOUPE;
	public static final RegistryObject<Item> CANTALOUPE_SLICE;
	public static final RegistryObject<Item> CANTALOUPE_PLANT;
	public static final RegistryObject<Item> LEMON_SAPLING;
	public static final RegistryObject<Item> BENZOIN_SAPLING;
	public static final RegistryObject<Item> GRAPEFRUIT_SAPLING;
	public static final RegistryObject<Item> LAVENDER_SAPLING;
	public static final RegistryObject<Item> MINT_SAPLING;
	public static final RegistryObject<Item> OAKMOSS_SAPLING;
	public static final RegistryObject<Item> PINE_OIL_SAPLING;
	public static final RegistryObject<Item> TONKA_SAPLING;
	public static final RegistryObject<Item> YLANG_YLANG_SAPLING;
	public static final RegistryObject<Item> PINE_CONE;
	public static final RegistryObject<Item> WAFFLE;
	public static final RegistryObject<Item> WAFFLE_CONE;
	public static final RegistryObject<Item> RAW_WAFFLE;
	public static final RegistryObject<Item> BATTER_BOWL;
	public static final RegistryObject<Item> RAW_PANCAKES;
	public static final RegistryObject<Item> PANCAKES;
	public static final RegistryObject<Item> BUTTERED_PANCAKES;
	public static final RegistryObject<Item> WALNUT;
	public static final RegistryObject<Item> WALNUT_SHELL;
	public static final RegistryObject<Item> ORANGE_SAPLING;
	public static final RegistryObject<Item> LIME_SAPLING;
	public static final RegistryObject<Item> HONEYDEW;
	public static final RegistryObject<Item> HONEYDEW_PLANT;
	public static final RegistryObject<Item> HONEYDEW_SLICE;
	public static final RegistryObject<Item> CORN_STARCH;
	public static final RegistryObject<Item> MOCHI;
	public static final RegistryObject<Item> RICE;
	public static final RegistryObject<Item> RICE_BOWL;
	public static final RegistryObject<Item> STICKY_RICE;
	public static final RegistryObject<Item> SUSHI_RICE;
	public static final RegistryObject<Item> HUNGER_HAUNCH;
	public static final RegistryObject<Item> REGENERATION_HEART;
	public static final RegistryObject<Item> WITHER_HEART;
	public static final RegistryObject<Item> HEALTH_BOOST_HEART;
	public static final RegistryObject<Item> BLINDNESS_EYE;
	public static final RegistryObject<Item> NIGHT_VISION_EYE;
	public static final RegistryObject<Item> INSTANT_HEALTH_HEART;
	public static final RegistryObject<Item> INSTANT_DAMAGE_HEART;
	public static final RegistryObject<Item> NAUSEA_STOMACH;
	public static final RegistryObject<Item> SATURATION_HAUNCH;
	public static final RegistryObject<Item> CONDUIT_POWER_HOTS;
	public static final RegistryObject<Item> RAID_OMEN_HEAD;
	public static final RegistryObject<Item> EMPTY_RAID_OMEN;
	public static final RegistryObject<Item> WEAVING_SPIDER;
	public static final RegistryObject<Item> INFESTED_SILVERFISH;
	public static final RegistryObject<Item> NAUTILUS;
	public static final RegistryObject<Item> DOLPHIN;
	public static final RegistryObject<Item> LUCK_CLOVER;
	public static final RegistryObject<Item> BAD_LUCK_CLOVER;
	public static final RegistryObject<Item> MAKIZUSHI_RICE;
	public static final RegistryObject<Item> SALMON_SUSHI;
	public static final RegistryObject<Item> SEA_SUSHI;
	public static final RegistryObject<Item> REGENERATION_SUSHI;
	public static final RegistryObject<Item> COD_SUSHI;
	public static final RegistryObject<Item> PUFFERFISH_SUSHI;
	public static final RegistryObject<Item> COOKED_PUFFERFISH_SUSHI;
	public static final RegistryObject<Item> NAREZUSHI_RICE;
	public static final RegistryObject<Item> COOKED_PUFFERFISH;
	public static final RegistryObject<Item> ZOMBIE_HAUNCH;
	public static final RegistryObject<Item> RAW_PATTY;
	public static final RegistryObject<Item> MEAT_PATTY;
	public static final RegistryObject<Item> RAW_MEAT_PATTY;
	public static final RegistryObject<Item> TROPICAL_FISH_SUSHI;
	public static final RegistryObject<Item> COOKED_TROPICAL_FISH;
	public static final RegistryObject<Item> RICE_PANICLE;
	public static final RegistryObject<Item> BEEF_SUSHI;
	public static final RegistryObject<Item> PORK_SUSHI;
	public static final RegistryObject<Item> CHICKEN_SUSHI;
	public static final RegistryObject<Item> MUTTON_SUSHI;
	public static final RegistryObject<Item> RABBIT_SUSHI;
	public static final RegistryObject<Item> ROTTEN_FLESH_SUSHI;
	public static final RegistryObject<Item> SPIDER_EYE_SUSHI;
	public static final RegistryObject<Item> LEATHER_SUSHI;
	public static final RegistryObject<Item> ENDER_DRAGON_SUSHI;
	public static final RegistryObject<Item> EVOKER_FANG_SUSHI;
	public static final RegistryObject<Item> OSHIZUSHI_RICE;
	public static final RegistryObject<Item> RAW_TOFU;
	public static final RegistryObject<Item> COOKED_TOFU;
	public static final RegistryObject<Item> SOY_MILK;
	public static final RegistryObject<Item> HOGLIN_SUSHI;
	public static final RegistryObject<Item> ILLAGER_SUSHI;
	public static final RegistryObject<Item> RAVAGER_SUSHI;
	public static final RegistryObject<Item> BREEZE_SUSHI;
	public static final RegistryObject<Item> CRISPY_HORSE_SUSHI;
	public static final RegistryObject<Item> ENDER_EYE_SUSHI;
	public static final RegistryObject<Item> GREEN_HAM_SUSHI;
	public static final RegistryObject<Item> MUMMY_SUSHI;
	public static final RegistryObject<Item> ENDERMITE_SUSHI;
	public static final RegistryObject<Item> WINTER_SUSHI;
	public static final RegistryObject<Item> GLOWING_FISH_SUSHI;
	public static final RegistryObject<Item> HUNGER_SUSHI;
	public static final RegistryObject<Item> WITHER_HEART_SUSHI;
	public static final RegistryObject<Item> BLINDNESS_SUSHI;
	public static final RegistryObject<Item> NIGHT_VISION_SUSHI;
	public static final RegistryObject<Item> INSTANT_HEALTH_SUSHI;
	public static final RegistryObject<Item> INSTANT_DAMAGE_SUSHI;
	public static final RegistryObject<Item> NAUSEA_SUSHI;
	public static final RegistryObject<Item> SILVERFISH_SUSHI;
	public static final RegistryObject<Item> BRAIN_SUSHI;
	public static final RegistryObject<Item> ENDER_PEARL_SUSHI;
	public static final RegistryObject<Item> POTATO_EYE_SUSHI;
	public static final RegistryObject<Item> ROTTEN_RIB_SUSHI;
	public static final RegistryObject<Item> PIGLIN_NOSE_SUSHI;
	public static final RegistryObject<Item> POTATO_EYE;
	public static final RegistryObject<Item> OOZING_SLIME;
	public static final RegistryObject<Item> CARING_HEART;
	public static final RegistryObject<Item> EXPIRED_MILK;
	static {
		CHOCOLATE = REGISTRY.register("chocolate", ChocolateItem::new);
		CHOCOLATE_CHIP = REGISTRY.register("chocolate_chip", ChocolateChipItem::new);
		DOUGH = REGISTRY.register("dough", DoughItem::new);
		COOKIE_DOUGH = REGISTRY.register("cookie_dough", CookieDoughItem::new);
		FLOUR = REGISTRY.register("flour", FlourItem::new);
		YEAST = REGISTRY.register("yeast", YeastItem::new);
		SALT = REGISTRY.register("salt", SaltItem::new);
		OIL_BOTTLE = REGISTRY.register("oil_bottle", OilBottleItem::new);
		BUTTER = REGISTRY.register("butter", ButterItem::new);
		CREAM_BUCKET = REGISTRY.register("cream_bucket", CreamBucketItem::new);
		CACAO_BUTTER_BOTTLE = REGISTRY.register("cacao_butter_bottle", CacaoButterBottleItem::new);
		CACAO_BUTTER = REGISTRY.register("cacao_butter", CacaoButterItem::new);
		BAKED_POISONOUS_POTATO = REGISTRY.register("baked_poisonous_potato", BakedPoisonousPotatoItem::new);
		POISONOUS_POTATO_STEW = REGISTRY.register("poisonous_potato_stew", PoisonousPotatoStewItem::new);
		POISONOUS_POTATO_NUBS = REGISTRY.register("poisonous_potato_nubs", PoisonousPotatoNubsItem::new);
		POTATO_STEW = REGISTRY.register("potato_stew", PotatoStewItem::new);
		CANDY = REGISTRY.register("candy", CandyItem::new);
		CUPCAKE = REGISTRY.register("cupcake", CupcakeItem::new);
		GELATIN = REGISTRY.register("gelatin", GelatinItem::new);
		ACTUAL_CHOCOLATE = REGISTRY.register("actual_chocolate", ActualChocolateItem::new);
		CHOCOLATE_DOUGH = REGISTRY.register("chocolate_dough", ChocolateDoughItem::new);
		CAKE_LAYER = REGISTRY.register("cake_layer", CakeLayerItem::new);
		INSTANT_CAKE = REGISTRY.register("instant_cake", InstantCakeItem::new);
		CAKE_SLICE = REGISTRY.register("cake_slice", CakeSliceItem::new);
		CUPCAKE_LAYER = REGISTRY.register("cupcake_layer", CupcakeLayerItem::new);
		SWEET_BERRY = REGISTRY.register("sweet_berry", SweetBerryItem::new);
		SWEET_BERRY_BOTTLE = REGISTRY.register("sweet_berry_bottle", SweetBerryBottleItem::new);
		MARSHMALLOW = REGISTRY.register("marshmallow", MarshmallowItem::new);
		MARSHMALLOW_STICK = REGISTRY.register("marshmallow_stick", MarshmallowStickItem::new);
		ROASTED_MARSHMALLOW_STICK = REGISTRY.register("roasted_marshmallow_stick", RoastedMarshmallowStickItem::new);
		WELLDONE_MARSHMALLOW = REGISTRY.register("welldone_marshmallow", WelldoneMarshmallowItem::new);
		BURNT_MARSHMALLOW_STICK = REGISTRY.register("burnt_marshmallow_stick", BurntMarshmallowStickItem::new);
		RAW_BISCUIT = REGISTRY.register("raw_biscuit", RawBiscuitItem::new);
		BISCUIT = REGISTRY.register("biscuit", BiscuitItem::new);
		SMORE = REGISTRY.register("smore", SmoreItem::new);
		ROASTED_SMORE = REGISTRY.register("roasted_smore", RoastedSmoreItem::new);
		WELLDONE_SMORE = REGISTRY.register("welldone_smore", WelldoneSmoreItem::new);
		BURNT_SMORE = REGISTRY.register("burnt_smore", BurntSmoreItem::new);
		GIANT_SMORE = REGISTRY.register("giant_smore", GiantSmoreItem::new);
		PINEAPPLE = REGISTRY.register("pineapple", PineappleItem::new);
		PINEAPPLE_SEEDS = REGISTRY.register("pineapple_seeds", PineappleSeedsItem::new);
		JELLY_JAR = REGISTRY.register("jelly_jar", JellyJarItem::new);
		JELLYFISH = REGISTRY.register("jellyfish", JellyfishItem::new);
		JELLYFISH_JELLY = REGISTRY.register("jellyfish_jelly", JellyfishJellyItem::new);
		KRABBY_PATTY = REGISTRY.register("krabby_patty", KrabbyPattyItem::new);
		PATTY = REGISTRY.register("patty", PattyItem::new);
		TOMATO = REGISTRY.register("tomato", TomatoItem::new);
		KETCHUP_BOTTLE = REGISTRY.register("ketchup_bottle", KetchupBottleItem::new);
		PLASTIC_CONDIMENT_BOTTLE = REGISTRY.register("plastic_condiment_bottle", PlasticCondimentBottleItem::new);
		MUSTARD_BOTTLE = REGISTRY.register("mustard_bottle", MustardBottleItem::new);
		MUSTARD_SEEDS = REGISTRY.register("mustard_seeds", MustardSeedsItem::new);
		CHEESE_BUCKET = REGISTRY.register("cheese_bucket", CheeseBucketItem::new);
		CHEESE = REGISTRY.register("cheese", CheeseItem::new);
		LETTUCE = REGISTRY.register("lettuce", LettuceItem::new);
		ONION = REGISTRY.register("onion", OnionItem::new);
		TOP_BUN = REGISTRY.register("top_bun", TopBunItem::new);
		BOTTOM_BUN = REGISTRY.register("bottom_bun", BottomBunItem::new);
		SESAME_SEEDS = REGISTRY.register("sesame_seeds", SesameSeedsItem::new);
		SESAME_BUN = REGISTRY.register("sesame_bun", SesameBunItem::new);
		KRABBY_PIZZA = REGISTRY.register("krabby_pizza", KrabbyPizzaItem::new);
		PIZZA_CRUST = REGISTRY.register("pizza_crust", PizzaCrustItem::new);
		PEPPERONI = REGISTRY.register("pepperoni", PepperoniItem::new);
		RAW_KRABBY_PIZZA = REGISTRY.register("raw_krabby_pizza", RawKrabbyPizzaItem::new);
		MAYONNAISE_JAR = REGISTRY.register("mayonnaise_jar", MayonnaiseJarItem::new);
		EMPTY_MAYO_JAR = REGISTRY.register("empty_mayo_jar", EmptyMayoJarItem::new);
		VINEGAR_BOTTLE = REGISTRY.register("vinegar_bottle", VinegarBottleItem::new);
		RAW_SESAME_BUN = REGISTRY.register("raw_sesame_bun", RawSesameBunItem::new);
		RAW_BOTTOM_BUN = REGISTRY.register("raw_bottom_bun", RawBottomBunItem::new);
		PLASTIC_ORE = block(MorefoodthaneverModBlocks.PLASTIC_ORE);
		DEEPSLATE_PLASTIC_ORE = block(MorefoodthaneverModBlocks.DEEPSLATE_PLASTIC_ORE);
		PLASTIC = REGISTRY.register("plastic", PlasticItem::new);
		RED_PLASTIC = REGISTRY.register("red_plastic", RedPlasticItem::new);
		BLUE_PLASTIC = REGISTRY.register("blue_plastic", BluePlasticItem::new);
		FROZEN_PATTY = REGISTRY.register("frozen_patty", FrozenPattyItem::new);
		LAVA_CHICKEN = REGISTRY.register("lava_chicken", LavaChickenItem::new);
		TATER_TOTS = REGISTRY.register("tater_tots", TaterTotsItem::new);
		CANDY_WRAPPER = REGISTRY.register("candy_wrapper", CandyWrapperItem::new);
		FROZEN_PATTY_BOX = REGISTRY.register("frozen_patty_box", FrozenPattyBoxItem::new);
		MAYONNAISE_LABEL = REGISTRY.register("mayonnaise_label", MayonnaiseLabelItem::new);
		CARDBOARD = REGISTRY.register("cardboard", CardboardItem::new);
		CHUM_BUCKET = REGISTRY.register("chum_bucket", ChumBucketItem::new);
		BIG_MAC_SAUCE = REGISTRY.register("big_mac_sauce", BigMacSauceItem::new);
		BLACK_PLASTIC = REGISTRY.register("black_plastic", BlackPlasticItem::new);
		GARLIC_POWDER = REGISTRY.register("garlic_powder", GarlicPowderItem::new);
		ONION_POWDER = REGISTRY.register("onion_powder", OnionPowderItem::new);
		PAPRIKA = REGISTRY.register("paprika", PaprikaItem::new);
		GARLIC = REGISTRY.register("garlic", GarlicItem::new);
		BELL_PEPPER = REGISTRY.register("bell_pepper", BellPepperItem::new);
		SALT_PEPPER = REGISTRY.register("salt_pepper", SaltPepperItem::new);
		CHILI_PEPPER = REGISTRY.register("chili_pepper", ChiliPepperItem::new);
		PEPPER = REGISTRY.register("pepper", PepperItem::new);
		BIG_MAC = REGISTRY.register("big_mac", BigMacItem::new);
		RAW_CENTER_BUN = REGISTRY.register("raw_center_bun", RawCenterBunItem::new);
		CENTER_BUN = REGISTRY.register("center_bun", CenterBunItem::new);
		FRENCH_FRY_BOX = REGISTRY.register("french_fry_box", FrenchFryBoxItem::new);
		FRENCH_FRIES = REGISTRY.register("french_fries", FrenchFriesItem::new);
		MC_NUGGETS = REGISTRY.register("mc_nuggets", McNuggetsItem::new);
		GLASS_CUP = REGISTRY.register("glass_cup", GlassCupItem::new);
		VANILLA = REGISTRY.register("vanilla", VanillaItem::new);
		ICE_CREAM_BUCKET = REGISTRY.register("ice_cream_bucket", IceCreamBucketItem::new);
		BLUEBERRIES = REGISTRY.register("blueberries", BlueberriesItem::new);
		RASPBERRY = REGISTRY.register("raspberry", RaspberryItem::new);
		STRAWBERRY = REGISTRY.register("strawberry", StrawberryItem::new);
		GRIMACE_SHAKE = REGISTRY.register("grimace_shake", GrimaceShakeItem::new);
		STRAW = REGISTRY.register("straw", StrawItem::new);
		YELLOW_PLASTIC = REGISTRY.register("yellow_plastic", YellowPlasticItem::new);
		NETHER_FLAME_SAUCE = REGISTRY.register("nether_flame_sauce", NetherFlameSauceItem::new);
		SAUCE_CONTAINER = REGISTRY.register("sauce_container", SauceContainerItem::new);
		BURGER_CRYSTAL = REGISTRY.register("burger_crystal", BurgerCrystalItem::new);
		CAYENNE_PEPPER = REGISTRY.register("cayenne_pepper", CayennePepperItem::new);
		TOMATO_PASTE = REGISTRY.register("tomato_paste", TomatoPasteItem::new);
		SALT_SUGAR = REGISTRY.register("salt_sugar", SaltSugarItem::new);
		RAW_BUN = REGISTRY.register("raw_bun", RawBunItem::new);
		MUG = REGISTRY.register("mug", MugItem::new);
		COFFEE_BEANS = REGISTRY.register("coffee_beans", CoffeeBeansItem::new);
		COFFEE_MUG = REGISTRY.register("coffee_mug", CoffeeMugItem::new);
		GLOW_DYE = REGISTRY.register("glow_dye", GlowDyeItem::new);
		GLOWING_BERRY = REGISTRY.register("glowing_berry", GlowingBerryItem::new);
		GLOWING_CARROT = REGISTRY.register("glowing_carrot", GlowingCarrotItem::new);
		GLOWING_FISH = REGISTRY.register("glowing_fish", GlowingFishItem::new);
		GLOWING_BONE = REGISTRY.register("glowing_bone", GlowingBoneItem::new);
		BOGGED_MOSS = REGISTRY.register("bogged_moss", BoggedMossItem::new);
		CRACKED_WITHER_SKULL = REGISTRY.register("cracked_wither_skull", CrackedWitherSkullItem::new);
		ELDER_GUARDIAN_EYE = REGISTRY.register("elder_guardian_eye", ElderGuardianEyeItem::new);
		ENDER_DRAGON_HAUNCH = REGISTRY.register("ender_dragon_haunch", EnderDragonHaunchItem::new);
		ENDER_SHELL = REGISTRY.register("ender_shell", EnderShellItem::new);
		EVOKER_FANG = REGISTRY.register("evoker_fang", EvokerFangItem::new);
		CREAKING_BARK = REGISTRY.register("creaking_bark", CreakingBarkItem::new);
		GUARDIAN_EYE = REGISTRY.register("guardian_eye", GuardianEyeItem::new);
		HOGLIN_MEAT = REGISTRY.register("hoglin_meat", HoglinMeatItem::new);
		ILLAGER_SHANK = REGISTRY.register("illager_shank", IllagerShankItem::new);
		PIGLIN_NOSE = REGISTRY.register("piglin_nose", PiglinNoseItem::new);
		RAVAGER_HAUNCH = REGISTRY.register("ravager_haunch", RavagerHaunchItem::new);
		SILVERFISH_SHELL = REGISTRY.register("silverfish_shell", SilverfishShellItem::new);
		SHULKER_GOO = REGISTRY.register("shulker_goo", ShulkerGooItem::new);
		VEX_WING = REGISTRY.register("vex_wing", VexWingItem::new);
		WARDEN_HORN = REGISTRY.register("warden_horn", WardenHornItem::new);
		WITHERED_BONE = REGISTRY.register("withered_bone", WitheredBoneItem::new);
		ENDER_SPICE = REGISTRY.register("ender_spice", EnderSpiceItem::new);
		NETHER_SPICE = REGISTRY.register("nether_spice", NetherSpiceItem::new);
		OMINOUS_SPICE = REGISTRY.register("ominous_spice", OminousSpiceItem::new);
		BATTERED_BREEZE_BALLS = REGISTRY.register("battered_breeze_balls", BatteredBreezeBallsItem::new);
		BLAZE_COCOA = REGISTRY.register("blaze_cocoa", BlazeCocoaItem::new);
		BOGGED_STEW = REGISTRY.register("bogged_stew", BoggedStewItem::new);
		BONE_SHAKE = REGISTRY.register("bone_shake", BoneShakeItem::new);
		BOOMSTICK_POPSICLE = REGISTRY.register("boomstick_popsicle", BoomstickPopsicleItem::new);
		BRAIN_JUICE = REGISTRY.register("brain_juice", BrainJuiceItem::new);
		CRISPY_HORSE_RIBS = REGISTRY.register("crispy_horse_ribs", CrispyHorseRibsItem::new);
		CRUNCHY_CUPCAKE = REGISTRY.register("crunchy_cupcake", CrunchyCupcakeItem::new);
		DRAGON_HOTPOT = REGISTRY.register("dragon_hotpot", DragonHotpotItem::new);
		DROWNED_STEW = REGISTRY.register("drowned_stew", DrownedStewItem::new);
		ELDER_GUARDIAN_SUSHI = REGISTRY.register("elder_guardian_sushi", ElderGuardianSushiItem::new);
		ENDER_LEMONADE = REGISTRY.register("ender_lemonade", EnderLemonadeItem::new);
		ENDER_EYE_SKEWER = REGISTRY.register("ender_eye_skewer", EnderEyeSkewerItem::new);
		FRIED_BONE_CHIPS = REGISTRY.register("fried_bone_chips", FriedBoneChipsItem::new);
		GHOST_CAKE = REGISTRY.register("ghost_cake", GhostCakeItem::new);
		GLAZED_ILLAGE_SKEWER = REGISTRY.register("glazed_illage_skewer", GlazedIllageSkewerItem::new);
		GREEN_HAM_AND_EGGS = REGISTRY.register("green_ham_and_eggs", GreenHamAndEggsItem::new);
		GUARDIAN_BROTH = REGISTRY.register("guardian_broth", GuardianBrothItem::new);
		MUMMY_WRAP = REGISTRY.register("mummy_wrap", MummyWrapItem::new);
		GUARDIAN_SUSHI = REGISTRY.register("guardian_sushi", GuardianSushiItem::new);
		HOGLIN_BROTH = REGISTRY.register("hoglin_broth", HoglinBrothItem::new);
		HOT_CHOCOLATE_CHURRO = REGISTRY.register("hot_chocolate_churro", HotChocolateChurroItem::new);
		ILLAGE_BURGER = REGISTRY.register("illage_burger", IllageBurgerItem::new);
		MAGMA_CREAM_COB = REGISTRY.register("magma_cream_cob", MagmaCreamCobItem::new);
		NIGHTMARE_BOBA_TEA = REGISTRY.register("nightmare_boba_tea", NightmareBobaTeaItem::new);
		OMINOUS_BERRY_PIE = REGISTRY.register("ominous_berry_pie", OminousBerryPieItem::new);
		PIGLIN_PIZZA = REGISTRY.register("piglin_pizza", PiglinPizzaItem::new);
		POISONED_CREAM_CONE = REGISTRY.register("poisoned_cream_cone", PoisonedCreamConeItem::new);
		RAVAGER_STEAK = REGISTRY.register("ravager_steak", RavagerSteakItem::new);
		ROTTEN_NOSEMALLOW = REGISTRY.register("rotten_nosemallow", RottenNosemallowItem::new);
		ROTTEN_RIBS = REGISTRY.register("rotten_ribs", RottenRibsItem::new);
		SHULKER_SPAGHETTI = REGISTRY.register("shulker_spaghetti", ShulkerSpaghettiItem::new);
		SILVER_SEAFOOD = REGISTRY.register("silver_seafood", SilverSeafoodItem::new);
		SLIME_STEW = REGISTRY.register("slime_stew", SlimeStewItem::new);
		SODA_BREEZE = REGISTRY.register("soda_breeze", SodaBreezeItem::new);
		SOUL_FLASK = REGISTRY.register("soul_flask", SoulFlaskItem::new);
		SOUL_SLORP = REGISTRY.register("soul_slorp", SoulSlorpItem::new);
		STUFFED_ENDERMITE = REGISTRY.register("stuffed_endermite", StuffedEndermiteItem::new);
		STUFFED_STUMP = REGISTRY.register("stuffed_stump", StuffedStumpItem::new);
		SWAMP_LATTE = REGISTRY.register("swamp_latte", SwampLatteItem::new);
		VEXED_SANDWICH = REGISTRY.register("vexed_sandwich", VexedSandwichItem::new);
		WARDEN_CAKE = REGISTRY.register("warden_cake", WardenCakeItem::new);
		WEBBED_CREAM_CONE = REGISTRY.register("webbed_cream_cone", WebbedCreamConeItem::new);
		WINTER_WRAP = REGISTRY.register("winter_wrap", WinterWrapItem::new);
		WITHER_SKULL_SUB = REGISTRY.register("wither_skull_sub", WitherSkullSubItem::new);
		WITHERED_BONEDOG = REGISTRY.register("withered_bonedog", WitheredBonedogItem::new);
		COCOA_MUG = REGISTRY.register("cocoa_mug", CocoaMugItem::new);
		LEMON_SLICE = REGISTRY.register("lemon_slice", LemonSliceItem::new);
		GRAPEFRUIT_SLICE = REGISTRY.register("grapefruit_slice", GrapefruitSliceItem::new);
		LAVENDER = REGISTRY.register("lavender", LavenderItem::new);
		MINT = REGISTRY.register("mint", MintItem::new);
		PINE_OIL = REGISTRY.register("pine_oil", PineOilItem::new);
		SEAWEED = REGISTRY.register("seaweed", SeaweedItem::new);
		YLANG_YLANG = REGISTRY.register("ylang_ylang", YlangYlangItem::new);
		BENZOIN = REGISTRY.register("benzoin", BenzoinItem::new);
		CEDARWOOD = REGISTRY.register("cedarwood", CedarwoodItem::new);
		TONKA = REGISTRY.register("tonka", TonkaItem::new);
		OAKMOSS = REGISTRY.register("oakmoss", OakmossItem::new);
		PINEAPPLE_PEEL = REGISTRY.register("pineapple_peel", PineapplePeelItem::new);
		CONSUMABLE_SUGAR = REGISTRY.register("consumable_sugar", ConsumableSugarItem::new);
		CONSUMABLE_SUGAR_CANE = REGISTRY.register("consumable_sugar_cane", ConsumableSugarCaneItem::new);
		ORANGE_SLICE = REGISTRY.register("orange_slice", OrangeSliceItem::new);
		SODA_POTION = REGISTRY.register("soda_potion", SodaPotionItem::new);
		DYNAMITE = REGISTRY.register("dynamite", DynamiteItem::new);
		WAX_BLOCK = block(MorefoodthaneverModBlocks.WAX_BLOCK);
		FRIED_EGG = REGISTRY.register("fried_egg", FriedEggItem::new);
		EDIBLE_KELP = REGISTRY.register("edible_kelp", EdibleKelpItem::new);
		EDIBLE_NETHER_WART = REGISTRY.register("edible_nether_wart", EdibleNetherWartItem::new);
		DRINKABLE_WATER_BUCKET = REGISTRY.register("drinkable_water_bucket", DrinkableWaterBucketItem::new);
		EDIBLE_SNOWBALL = REGISTRY.register("edible_snowball", EdibleSnowballItem::new);
		EDIBLE_WHEAT_SEEDS = REGISTRY.register("edible_wheat_seeds", EdibleWheatSeedsItem::new);
		EDIBLE_MELON_SEEDS = REGISTRY.register("edible_melon_seeds", EdibleMelonSeedsItem::new);
		EDIBLE_PUMPKIN_SEEDS = REGISTRY.register("edible_pumpkin_seeds", EdiblePumpkinSeedsItem::new);
		EDIBLE_BEETROOT_SEEDS = REGISTRY.register("edible_beetroot_seeds", EdibleBeetrootSeedsItem::new);
		EDIBLE_POWDER_SNOW_BUCKET = REGISTRY.register("edible_powder_snow_bucket", EdiblePowderSnowBucketItem::new);
		EDIBLE_COCOA_BEANS = REGISTRY.register("edible_cocoa_beans", EdibleCocoaBeansItem::new);
		EDIBLE_HONEYCOMB = REGISTRY.register("edible_honeycomb", EdibleHoneycombItem::new);
		EDIBLE_EGG = REGISTRY.register("edible_egg", EdibleEggItem::new);
		EGG_SHELL = REGISTRY.register("egg_shell", EggShellItem::new);
		EDIBLE_TURTLE_EGG = REGISTRY.register("edible_turtle_egg", EdibleTurtleEggItem::new);
		TURTLE_EGG_SHELL = REGISTRY.register("turtle_egg_shell", TurtleEggShellItem::new);
		CRYSTALLIZED_HONEY = REGISTRY.register("crystallized_honey", CrystallizedHoneyItem::new);
		BANANA = REGISTRY.register("banana", BananaItem::new);
		NACHO = REGISTRY.register("nacho", NachoItem::new);
		CORN = REGISTRY.register("corn", CornItem::new);
		BLACKBERRY = REGISTRY.register("blackberry", BlackberryItem::new);
		GRAPES = REGISTRY.register("grapes", GrapesItem::new);
		PEANUT = REGISTRY.register("peanut", PeanutItem::new);
		PEANUT_SHELL = REGISTRY.register("peanut_shell", PeanutShellItem::new);
		CUCUMBER = REGISTRY.register("cucumber", CucumberItem::new);
		CRANBERRIES = REGISTRY.register("cranberries", CranberriesItem::new);
		TURNIP = REGISTRY.register("turnip", TurnipItem::new);
		KIWI = REGISTRY.register("kiwi", KiwiItem::new);
		TURMERIC = REGISTRY.register("turmeric", TurmericItem::new);
		LIME_SLICE = REGISTRY.register("lime_slice", LimeSliceItem::new);
		LEMON = REGISTRY.register("lemon", LemonItem::new);
		GRAPEFRUIT = REGISTRY.register("grapefruit", GrapefruitItem::new);
		ORANGE = REGISTRY.register("orange", OrangeItem::new);
		LIME = REGISTRY.register("lime", LimeItem::new);
		PEAR = REGISTRY.register("pear", PearItem::new);
		PEACH = REGISTRY.register("peach", PeachItem::new);
		AVOCADO = REGISTRY.register("avocado", AvocadoItem::new);
		COCONUT = REGISTRY.register("coconut", CoconutItem::new);
		COCONUT_SHELL = REGISTRY.register("coconut_shell", CoconutShellItem::new);
		COCONUT_HALF = REGISTRY.register("coconut_half", CoconutHalfItem::new);
		CHERRIES = REGISTRY.register("cherries", CherriesItem::new);
		OLIVES = REGISTRY.register("olives", OlivesItem::new);
		POMEGRANATE = REGISTRY.register("pomegranate", PomegranateItem::new);
		ACORN = REGISTRY.register("acorn", AcornItem::new);
		PLUM = REGISTRY.register("plum", PlumItem::new);
		PITAHAYA = REGISTRY.register("pitahaya", PitahayaItem::new);
		PITAHAYA_PEEL = REGISTRY.register("pitahaya_peel", PitahayaPeelItem::new);
		AVOCADO_HALF = REGISTRY.register("avocado_half", AvocadoHalfItem::new);
		AVOCADO_PEEL = REGISTRY.register("avocado_peel", AvocadoPeelItem::new);
		AVOCADO_PEEL_HALF = REGISTRY.register("avocado_peel_half", AvocadoPeelHalfItem::new);
		COCONUT_SHELL_HALF = REGISTRY.register("coconut_shell_half", CoconutShellHalfItem::new);
		KIWIFRUIT = REGISTRY.register("kiwifruit", KiwifruitItem::new);
		TEA_LEAVES = REGISTRY.register("tea_leaves", TeaLeavesItem::new);
		RAW_TORTILLA = REGISTRY.register("raw_tortilla", RawTortillaItem::new);
		TORTILLA = REGISTRY.register("tortilla", TortillaItem::new);
		TORTILLA_CHIP = REGISTRY.register("tortilla_chip", TortillaChipItem::new);
		MANGO = REGISTRY.register("mango", MangoItem::new);
		MANGO_SKIN = REGISTRY.register("mango_skin", MangoSkinItem::new);
		GREEN_BEAN = REGISTRY.register("green_bean", GreenBeanItem::new);
		SOUR_BERRIES = REGISTRY.register("sour_berries", SourBerriesItem::new);
		SOUR_BERRY_BUSH = block(MorefoodthaneverModBlocks.SOUR_BERRY_BUSH);
		SOYBEAN_POD = REGISTRY.register("soybean_pod", SoybeanPodItem::new);
		SOYBEANS = REGISTRY.register("soybeans", SoybeansItem::new);
		COOKED_SOYBEANS = REGISTRY.register("cooked_soybeans", CookedSoybeansItem::new);
		EMPTY_SOYBEAN_POD = REGISTRY.register("empty_soybean_pod", EmptySoybeanPodItem::new);
		HUCKLEBERRIES = REGISTRY.register("huckleberries", HuckleberriesItem::new);
		CHOCOLATE_STRAWBERRY = REGISTRY.register("chocolate_strawberry", ChocolateStrawberryItem::new);
		PRICKLY_PEAR = REGISTRY.register("prickly_pear", PricklyPearItem::new);
		LINGONBERRIES = REGISTRY.register("lingonberries", LingonberriesItem::new);
		CANTALOUPE = block(MorefoodthaneverModBlocks.CANTALOUPE);
		CANTALOUPE_SLICE = REGISTRY.register("cantaloupe_slice", CantaloupeSliceItem::new);
		CANTALOUPE_PLANT = block(MorefoodthaneverModBlocks.CANTALOUPE_PLANT);
		LEMON_SAPLING = block(MorefoodthaneverModBlocks.LEMON_SAPLING);
		BENZOIN_SAPLING = block(MorefoodthaneverModBlocks.BENZOIN_SAPLING);
		GRAPEFRUIT_SAPLING = block(MorefoodthaneverModBlocks.GRAPEFRUIT_SAPLING);
		LAVENDER_SAPLING = block(MorefoodthaneverModBlocks.LAVENDER_SAPLING);
		MINT_SAPLING = block(MorefoodthaneverModBlocks.MINT_SAPLING);
		OAKMOSS_SAPLING = block(MorefoodthaneverModBlocks.OAKMOSS_SAPLING);
		PINE_OIL_SAPLING = block(MorefoodthaneverModBlocks.PINE_OIL_SAPLING);
		TONKA_SAPLING = block(MorefoodthaneverModBlocks.TONKA_SAPLING);
		YLANG_YLANG_SAPLING = block(MorefoodthaneverModBlocks.YLANG_YLANG_SAPLING);
		PINE_CONE = REGISTRY.register("pine_cone", PineConeItem::new);
		WAFFLE = REGISTRY.register("waffle", WaffleItem::new);
		WAFFLE_CONE = REGISTRY.register("waffle_cone", WaffleConeItem::new);
		RAW_WAFFLE = REGISTRY.register("raw_waffle", RawWaffleItem::new);
		BATTER_BOWL = REGISTRY.register("batter_bowl", BatterBowlItem::new);
		RAW_PANCAKES = REGISTRY.register("raw_pancakes", RawPancakesItem::new);
		PANCAKES = REGISTRY.register("pancakes", PancakesItem::new);
		BUTTERED_PANCAKES = REGISTRY.register("buttered_pancakes", ButteredPancakesItem::new);
		WALNUT = REGISTRY.register("walnut", WalnutItem::new);
		WALNUT_SHELL = REGISTRY.register("walnut_shell", WalnutShellItem::new);
		ORANGE_SAPLING = block(MorefoodthaneverModBlocks.ORANGE_SAPLING);
		LIME_SAPLING = block(MorefoodthaneverModBlocks.LIME_SAPLING);
		HONEYDEW = block(MorefoodthaneverModBlocks.HONEYDEW);
		HONEYDEW_PLANT = block(MorefoodthaneverModBlocks.HONEYDEW_PLANT);
		HONEYDEW_SLICE = REGISTRY.register("honeydew_slice", HoneydewSliceItem::new);
		CORN_STARCH = REGISTRY.register("corn_starch", CornStarchItem::new);
		MOCHI = REGISTRY.register("mochi", MochiItem::new);
		RICE = REGISTRY.register("rice", RiceItem::new);
		RICE_BOWL = REGISTRY.register("rice_bowl", RiceBowlItem::new);
		STICKY_RICE = REGISTRY.register("sticky_rice", StickyRiceItem::new);
		SUSHI_RICE = REGISTRY.register("sushi_rice", SushiRiceItem::new);
		HUNGER_HAUNCH = REGISTRY.register("hunger_haunch", HungerHaunchItem::new);
		REGENERATION_HEART = REGISTRY.register("regeneration_heart", RegenerationHeartItem::new);
		WITHER_HEART = REGISTRY.register("wither_heart", WitherHeartItem::new);
		HEALTH_BOOST_HEART = REGISTRY.register("health_boost_heart", HealthBoostHeartItem::new);
		BLINDNESS_EYE = REGISTRY.register("blindness_eye", BlindnessEyeItem::new);
		NIGHT_VISION_EYE = REGISTRY.register("night_vision_eye", NightVisionEyeItem::new);
		INSTANT_HEALTH_HEART = REGISTRY.register("instant_health_heart", InstantHealthHeartItem::new);
		INSTANT_DAMAGE_HEART = REGISTRY.register("instant_damage_heart", InstantDamageHeartItem::new);
		NAUSEA_STOMACH = REGISTRY.register("nausea_stomach", NauseaStomachItem::new);
		SATURATION_HAUNCH = REGISTRY.register("saturation_haunch", SaturationHaunchItem::new);
		CONDUIT_POWER_HOTS = REGISTRY.register("conduit_power_hots", ConduitPowerHOTSItem::new);
		RAID_OMEN_HEAD = REGISTRY.register("raid_omen_head", RaidOmenHeadItem::new);
		EMPTY_RAID_OMEN = REGISTRY.register("empty_raid_omen", EmptyRaidOmenItem::new);
		WEAVING_SPIDER = REGISTRY.register("weaving_spider", WeavingSpiderItem::new);
		INFESTED_SILVERFISH = REGISTRY.register("infested_silverfish", InfestedSilverfishItem::new);
		NAUTILUS = REGISTRY.register("nautilus", NautilusItem::new);
		DOLPHIN = REGISTRY.register("dolphin", DolphinItem::new);
		LUCK_CLOVER = REGISTRY.register("luck_clover", LuckCloverItem::new);
		BAD_LUCK_CLOVER = REGISTRY.register("bad_luck_clover", BadLuckCloverItem::new);
		MAKIZUSHI_RICE = REGISTRY.register("makizushi_rice", MakizushiRiceItem::new);
		SALMON_SUSHI = REGISTRY.register("salmon_sushi", SalmonSushiItem::new);
		SEA_SUSHI = REGISTRY.register("sea_sushi", SeaSushiItem::new);
		REGENERATION_SUSHI = REGISTRY.register("regeneration_sushi", RegenerationSushiItem::new);
		COD_SUSHI = REGISTRY.register("cod_sushi", CodSushiItem::new);
		PUFFERFISH_SUSHI = REGISTRY.register("pufferfish_sushi", PufferfishSushiItem::new);
		COOKED_PUFFERFISH_SUSHI = REGISTRY.register("cooked_pufferfish_sushi", CookedPufferfishSushiItem::new);
		NAREZUSHI_RICE = REGISTRY.register("narezushi_rice", NarezushiRiceItem::new);
		COOKED_PUFFERFISH = REGISTRY.register("cooked_pufferfish", CookedPufferfishItem::new);
		ZOMBIE_HAUNCH = REGISTRY.register("zombie_haunch", ZombieHaunchItem::new);
		RAW_PATTY = REGISTRY.register("raw_patty", RawPattyItem::new);
		MEAT_PATTY = REGISTRY.register("meat_patty", MeatPattyItem::new);
		RAW_MEAT_PATTY = REGISTRY.register("raw_meat_patty", RawMeatPattyItem::new);
		TROPICAL_FISH_SUSHI = REGISTRY.register("tropical_fish_sushi", TropicalFishSushiItem::new);
		COOKED_TROPICAL_FISH = REGISTRY.register("cooked_tropical_fish", CookedTropicalFishItem::new);
		RICE_PANICLE = block(MorefoodthaneverModBlocks.RICE_PANICLE);
		BEEF_SUSHI = REGISTRY.register("beef_sushi", BeefSushiItem::new);
		PORK_SUSHI = REGISTRY.register("pork_sushi", PorkSushiItem::new);
		CHICKEN_SUSHI = REGISTRY.register("chicken_sushi", ChickenSushiItem::new);
		MUTTON_SUSHI = REGISTRY.register("mutton_sushi", MuttonSushiItem::new);
		RABBIT_SUSHI = REGISTRY.register("rabbit_sushi", RabbitSushiItem::new);
		ROTTEN_FLESH_SUSHI = REGISTRY.register("rotten_flesh_sushi", RottenFleshSushiItem::new);
		SPIDER_EYE_SUSHI = REGISTRY.register("spider_eye_sushi", SpiderEyeSushiItem::new);
		LEATHER_SUSHI = REGISTRY.register("leather_sushi", LeatherSushiItem::new);
		ENDER_DRAGON_SUSHI = REGISTRY.register("ender_dragon_sushi", EnderDragonSushiItem::new);
		EVOKER_FANG_SUSHI = REGISTRY.register("evoker_fang_sushi", EvokerFangSushiItem::new);
		OSHIZUSHI_RICE = REGISTRY.register("oshizushi_rice", OshizushiRiceItem::new);
		RAW_TOFU = REGISTRY.register("raw_tofu", RawTofuItem::new);
		COOKED_TOFU = REGISTRY.register("cooked_tofu", CookedTofuItem::new);
		SOY_MILK = REGISTRY.register("soy_milk", SoyMilkItem::new);
		HOGLIN_SUSHI = REGISTRY.register("hoglin_sushi", HoglinSushiItem::new);
		ILLAGER_SUSHI = REGISTRY.register("illager_sushi", IllagerSushiItem::new);
		RAVAGER_SUSHI = REGISTRY.register("ravager_sushi", RavagerSushiItem::new);
		BREEZE_SUSHI = REGISTRY.register("breeze_sushi", BreezeSushiItem::new);
		CRISPY_HORSE_SUSHI = REGISTRY.register("crispy_horse_sushi", CrispyHorseSushiItem::new);
		ENDER_EYE_SUSHI = REGISTRY.register("ender_eye_sushi", EnderEyeSushiItem::new);
		GREEN_HAM_SUSHI = REGISTRY.register("green_ham_sushi", GreenHamSushiItem::new);
		MUMMY_SUSHI = REGISTRY.register("mummy_sushi", MummySushiItem::new);
		ENDERMITE_SUSHI = REGISTRY.register("endermite_sushi", EndermiteSushiItem::new);
		WINTER_SUSHI = REGISTRY.register("winter_sushi", WinterSushiItem::new);
		GLOWING_FISH_SUSHI = REGISTRY.register("glowing_fish_sushi", GlowingFishSushiItem::new);
		HUNGER_SUSHI = REGISTRY.register("hunger_sushi", HungerSushiItem::new);
		WITHER_HEART_SUSHI = REGISTRY.register("wither_heart_sushi", WitherHeartSushiItem::new);
		BLINDNESS_SUSHI = REGISTRY.register("blindness_sushi", BlindnessSushiItem::new);
		NIGHT_VISION_SUSHI = REGISTRY.register("night_vision_sushi", NightVisionSushiItem::new);
		INSTANT_HEALTH_SUSHI = REGISTRY.register("instant_health_sushi", InstantHealthSushiItem::new);
		INSTANT_DAMAGE_SUSHI = REGISTRY.register("instant_damage_sushi", InstantDamageSushiItem::new);
		NAUSEA_SUSHI = REGISTRY.register("nausea_sushi", NauseaSushiItem::new);
		SILVERFISH_SUSHI = REGISTRY.register("silverfish_sushi", SilverfishSushiItem::new);
		BRAIN_SUSHI = REGISTRY.register("brain_sushi", BrainSushiItem::new);
		ENDER_PEARL_SUSHI = REGISTRY.register("ender_pearl_sushi", EnderPearlSushiItem::new);
		POTATO_EYE_SUSHI = REGISTRY.register("potato_eye_sushi", PotatoEyeSushiItem::new);
		ROTTEN_RIB_SUSHI = REGISTRY.register("rotten_rib_sushi", RottenRibSushiItem::new);
		PIGLIN_NOSE_SUSHI = REGISTRY.register("piglin_nose_sushi", PiglinNoseSushiItem::new);
		POTATO_EYE = REGISTRY.register("potato_eye", PotatoEyeItem::new);
		OOZING_SLIME = REGISTRY.register("oozing_slime", OozingSlimeItem::new);
		CARING_HEART = REGISTRY.register("caring_heart", CaringHeartItem::new);
		EXPIRED_MILK = REGISTRY.register("expired_milk", ExpiredMilkItem::new);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static RegistryObject<Item> block(RegistryObject<Block> block) {
		return block(block, new Item.Properties());
	}

	private static RegistryObject<Item> block(RegistryObject<Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}